weights:
  w_obj: 1e-4
  w_slack: 1.0
  w_con: 1.0
  w_sup: 0.0

training:
  TRAINING_EPOCHS: 5
  CHECKPOINT_AFTER: 50
  LEARNING_RATE: 1e-3
  WEIGHT_DECAY: 1e-5
  PATIENCE: 10
  WANDB_PROJECT: l2o_ssl_miqp_robot_nav
  RUN_NAME_PREFIX: ssl_