weights:
  w_obj: 0.0
  w_slack: 0.0
  w_con: 0.0
  w_sup: 1e0

training:
  TRAINING_EPOCHS: 10
  CHECKPOINT_AFTER: 50
  LEARNING_RATE: 1e-3
  WEIGHT_DECAY: 1e-5
  PATIENCE: 10
  WANDB_PROJECT: l2o_ssl_miqp_energy
  RUN_NAME_PREFIX: ssl_